import 'dart:ffi';
import 'dart:io';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

/// dart:ffi binding to the tiny native decoder built from
/// native/zstddeclib.c -- Facebook's official single-file, decode-only
/// amalgamation of libzstd (generated by zstd's own
/// build/single_file_libs/create_single_file_decoder.sh, unmodified
/// upstream source). No pure-Dart zstd decoder exists, and almost every
/// .zim archive produced since ~2021 compresses its clusters with zstd, so
/// reading .zim files fully offline (no server involved) needs this.
///
/// The library is bundled per platform: Android ships prebuilt .so files
/// per ABI under android/app/src/main/jniLibs/ (Gradle packages these into
/// the APK automatically); Linux and Windows compile native/zstddeclib.c
/// as part of their own CMake build (see linux/CMakeLists.txt,
/// windows/CMakeLists.txt) and install the result next to the app binary.
class _Bindings {
  final DynamicLibrary lib;
  _Bindings(this.lib);

  late final createDCtx = lib.lookupFunction<Pointer<Void> Function(), Pointer<Void> Function()>('ZSTD_createDCtx');
  late final freeDCtx =
      lib.lookupFunction<Size Function(Pointer<Void>), int Function(Pointer<Void>)>('ZSTD_freeDCtx');
  late final decompressStream = lib.lookupFunction<
      Size Function(Pointer<Void>, Pointer<_OutBuffer>, Pointer<_InBuffer>),
      int Function(Pointer<Void>, Pointer<_OutBuffer>, Pointer<_InBuffer>)>('ZSTD_decompressStream');
  late final isError =
      lib.lookupFunction<Uint32 Function(Size), int Function(int)>('ZSTD_isError');
  late final dStreamOutSize =
      lib.lookupFunction<Size Function(), int Function()>('ZSTD_DStreamOutSize');
}

// Mirrors ZSTD_inBuffer / ZSTD_outBuffer from zstd.h: {src/dst, size, pos}
// (a Pointer<Void> + two `size_t`s each, in that field order).
final class _InBuffer extends Struct {
  external Pointer<Void> src;
  @Size()
  external int size;
  @Size()
  external int pos;
}

final class _OutBuffer extends Struct {
  external Pointer<Void> dst;
  @Size()
  external int size;
  @Size()
  external int pos;
}

_Bindings? _bindings;

_Bindings _load() {
  final existing = _bindings;
  if (existing != null) return existing;
  final DynamicLibrary lib;
  if (Platform.isAndroid || Platform.isLinux) {
    lib = DynamicLibrary.open('libzstddec.so');
  } else if (Platform.isWindows) {
    lib = DynamicLibrary.open('zstddec.dll');
  } else {
    throw UnsupportedError('zstd decoding is not bundled for ${Platform.operatingSystem}');
  }
  final b = _Bindings(lib);
  _bindings = b;
  return b;
}

/// Decompresses one complete zstd frame (a .zim cluster's payload, minus its
/// 1-byte compression-type marker) using the streaming API -- most .zim
/// clusters are written without a content-size field in the frame header
/// (ZSTD_getFrameContentSize returns "unknown"), so a fixed-size one-shot
/// buffer isn't an option; the output buffer grows as needed instead.
Uint8List zstdDecompress(Uint8List compressed) {
  final b = _load();
  final dctx = b.createDCtx();
  if (dctx == nullptr) throw StateError('ZSTD_createDCtx failed');
  try {
    final inPtr = malloc<Uint8>(compressed.length);
    inPtr.asTypedList(compressed.length).setAll(0, compressed);
    final inBuf = malloc<_InBuffer>();
    inBuf.ref
      ..src = inPtr.cast()
      ..size = compressed.length
      ..pos = 0;

    var outCapacity = b.dStreamOutSize();
    if (outCapacity <= 0) outCapacity = 1 << 17;
    var out = Uint8List(outCapacity);
    var outLen = 0;

    final outBuf = malloc<_OutBuffer>();
    try {
      while (inBuf.ref.pos < inBuf.ref.size) {
        if (outCapacity - outLen < 65536) {
          final grown = Uint8List(outCapacity * 2);
          grown.setAll(0, out.sublist(0, outLen));
          out = grown;
          outCapacity = out.length;
        }
        final chunkPtr = malloc<Uint8>(outCapacity - outLen);
        outBuf.ref
          ..dst = chunkPtr.cast()
          ..size = outCapacity - outLen
          ..pos = 0;
        final ret = b.decompressStream(dctx, outBuf, inBuf);
        if (b.isError(ret) != 0) {
          malloc.free(chunkPtr);
          throw const FormatException('zstd stream decompression failed (corrupt cluster?)');
        }
        out.setRange(outLen, outLen + outBuf.ref.pos, chunkPtr.asTypedList(outBuf.ref.pos));
        outLen += outBuf.ref.pos;
        malloc.free(chunkPtr);
        if (ret == 0) break; // frame complete
      }
    } finally {
      malloc.free(outBuf);
      malloc.free(inPtr);
      malloc.free(inBuf);
    }
    return Uint8List.sublistView(out, 0, outLen);
  } finally {
    b.freeDCtx(dctx);
  }
}
